swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0

host: api.example.com
basePath: /v1
schemes:
  - https

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/User'
        201:
          description: OK
          schema:
            $ref: '#/definitions/FlatUser'

definitions:
  User:
    type: object
    properties:
      names:
        $ref: '#/definitions/Names'
  FlatUser:
    type: object
    properties:
      broken:
        type: object
        properties:
          field1:
            type: string
          field2:
            type: string
    allOf:
      - $ref: '#/definitions/Names'
      - $ref: '#/definitions/Address'
  Names:
    type: object
    properties:
      firstName:
        type: string
      middleName:
        type: string
      lastName:
        type: string
  Address:
    type: object
    properties:
      street:
        type: string
      city:
        type: string
  Broken:
    type: object
    properties:
      field1:
        type: string
      field2:
        type: string
